'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ghost_game.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ g g g g g g g g g g g g g g g ,
        '''_ C - - - - - - - - - - - - - - ,
        '''- - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ w - - - - - - - - - - - - - - ,
        '''_ w w - - - - - - - - - - - - - ,
        '''_ m - - - - - - - - -  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _0() As String
            Get
                Return ResourceManager.GetString("_0", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to - - - - - - - - - - - - - - - - ,
        '''- - - - - - - - - - - - - - - - ,
        '''- - - - - - - - - - - - - - - - ,
        '''- - - - - - - - - - - - - - - - ,
        '''- - - - - - - - - - - - - - - - ,
        '''- - - - - - - - - - - - - - - - ,
        '''- - - - - - - - - - - - - - - - ,
        '''- - - - - - - - - - - - - - - - ,
        '''g g g g g g g g g g g g g g g g ,
        '''w - - - - - - - - - - - - C P - ,
        '''- - - - - - - - - - - - - - - - ,
        '''w w - - - - - - - - - - - - - - ,
        '''- - - m - w w w w w w w w w w w ,
        '''- - - - - - - - - - - - - - - - ,
        '''w w - - - - - - - - -  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property _01() As String
            Get
                Return ResourceManager.GetString("_01", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cloud() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cloud", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cobbles() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cobbles", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property coin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("coin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property crown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("crown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dirt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dirt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fireball() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fireball", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frog_move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frog_move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grassy_dirt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grassy_dirt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property graveyard_dirt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graveyard_dirt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property heart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_dying() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_dying", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_dying_move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_dying_move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_hurt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_hurt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_hurt_move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_hurt_move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_invuln() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_invuln", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_move() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_move", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_move_invlun() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_move_invlun", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property player_shot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("player_shot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to _ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''_ - - - - - - - - - - - - - - - ,
        '''g g g g g g g g g g g g g g g g ,
        '''2 C - - - - - - - - - - - - - - ,
        '''2 5 5 4 1 3 5 5 3 1 1 2 1 4 3 3 ,
        '''5 3 1 2 1 1 4 3 5 1 4 5 3 2 1 ,
        '''2 4 3 2 5 3 3 3 5 2 4 1 3 5 4 ,
        '''5 4 3 1 3 5 1 5 5 3 1 4 5 3 2 ,
        '''1 5 1 2 1 4 1 2 3 3 1 5 4 2  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Random() As String
            Get
                Return ResourceManager.GetString("Random", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property shep() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("shep", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tavern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tavern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
